### ISSUE TITLE
ImportError: cannot import name MigratingIdentityId

### ISSUE THREAD

**Issue by robinboening** [getsentry/sentry-auth-google#23] opened 2017-11-30 14:05 UTC
I face an issue with the change introduced by this commit: d3f5cc4807b730d4dfcac8cfa9bf7c6d54c788ea

I am deploying sentry `v8.20.0` to heroku with current master of `sentry-auth-google` (as suggested in the readme https://github.com/getsentry/sentry-auth-google#install and here https://github.com/getsentry/sentry-auth-google/issues/16#issuecomment-334497931)

Backtrace
```
...
File "/app/.heroku/src/sentry-auth-google/sentry_auth_google/provider.py", line 3, in <module> from sentry.auth.provider import MigratingIdentityId
ImportError: cannot import name MigratingIdentityId
```

**Comment by robinboening** [comment] 2017-11-30 14:11
i do understand that this might not occur when using the latest sentry master since the MigrationIdentityId was jsut recently introduced with this commit https://github.com/getsentry/sentry/commit/2ee53ad1cc9a3f7f07bdcad2ba9bd4c6d3e8b1d1#diff-bc62100fd350490b1076de6090d2c37f

But as I said I am using the stable `v8.20.0` - and I actually want to keep using stable releases. :)

I'd like to refer to this discussion https://github.com/getsentry/sentry-auth-google/issues/16 which is about cutting a new release, so we don't need to use the master.

**Comment by rkraneis** [comment] 2017-11-30 16:10
I've been also just hit by this. I'm now trying out `https://github.com/getsentry/sentry-auth-google/archive/52020f577f587595fea55f5d05520f1473deaad1.zip` in `requirements.txt`.

**Comment by sreeram-boyapati** [comment] 2017-12-04 08:19
8.22 (latest release) was released 18 days ago. This change was made 12 days ago in master. 

sentry-auth-google does not have any release tags corresponding to sentry releases. (like sentry-plugins has 8.21 and 8.22 releases).

Pinning the requirement to 52020f577f587595fea55f5d05520f1473deaad1 has solved the problem.

**Comment by EvanPurkhiser** [comment] 2017-12-04 17:21
Duplicate of #21 

We're likely going to merge the auth plugins into sentry-plugins, or directly into sentry core.

**Closed by EvanPurkhiser** 2017-12-04 17:21 UTC
